import * as THREE from 'three';
import {OrbitControls} from './vendor/three/controls/OrbitControls.js';
import {GLTFLoader} from './vendor/three/loaders/GLTFLoader.js';
const $=s=>document.querySelector(s),el=$('#view');
const scene=new THREE.Scene();scene.background=new THREE.Color('#101916');
const camera=new THREE.PerspectiveCamera(35,1,.001,10);camera.position.set(.48,.35,.55);
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;el.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(-.02,.15,0);controls.enableDamping=true;controls.minDistance=.15;controls.maxDistance=1.8;
scene.add(new THREE.HemisphereLight(0xeaffdf,0x425441,3));const light=new THREE.DirectionalLight(0xffe7c1,3);light.position.set(1,2,1);scene.add(light);const fill=new THREE.DirectionalLight(0xb9e1fc,2);fill.position.set(-1,1,-1);scene.add(fill);scene.add(new THREE.GridHelper(1,20,0x41563d,0x233027));
let expanded=false,hideStock=false,selected=null;const items=[],bodyGroups=new Map(),jointControls=[];let parts,rig,root;
const fetchJSON=async url=>{const r=await fetch(url);if(!r.ok)throw Error(`${url}: ${r.status}`);return r.json()};
function select(mesh){if(selected)selected.material.emissive.setHex(0);selected=mesh;if(!mesh)return;mesh.material.emissive.setHex(0x284820);const entry=parts.find(p=>p.name===mesh.name);const metadata=rig.meshes[mesh.name];const box=$('#selection');box.replaceChildren();const h=document.createElement('h3');h.textContent=metadata?.label||mesh.name;box.append(h);const p=document.createElement('p');p.textContent=entry?`${entry.dimensions_mm.map(v=>v.toFixed(1)).join(' × ')} mm · ${entry.mass_g.toFixed(2)} g 추정 · ${entry.parent}`:`원본 Microduck 부품 · ${bodyGroups.get(metadata?.body)?.name||''}`;box.append(p);if(entry){for(const [label,path] of [['출력 STL',`models/print/${entry.name}.stl`],['CAD STEP',entry.step]]){const a=document.createElement('a');a.textContent=label+' ↓';a.href='../'+path;box.append(a)}}}
function applyExplode(){for(const mesh of items){mesh.position.copy(mesh.userData.base);if(expanded&&!mesh.name.startsWith('stock_'))mesh.position.add(mesh.userData.explode)}}
function setJoint(item,value){const {group,joint,basePos,baseQuat}=item;const q=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(...joint.axis),value);const pivot=new THREE.Vector3(...joint.pivot);group.quaternion.copy(baseQuat).multiply(q);group.position.copy(basePos).add(pivot.clone().sub(pivot.clone().applyQuaternion(q)).applyQuaternion(baseQuat));item.input.value=value;item.output.textContent=`${THREE.MathUtils.radToDeg(value).toFixed(0)}°`;}
try{
 const [g,p,r,v]=await Promise.all([new GLTFLoader().loadAsync('../models/micro_rex.glb'),fetchJSON('../artifacts/parts.json'),fetchJSON('../models/rig.json'),fetchJSON('../artifacts/validation.json')]);parts=p;rig=r;
 root=new THREE.Group();scene.add(root);bodyGroups.set(0,root);
 for(const b of rig.bodies){const group=new THREE.Group();group.name=b.name;group.position.fromArray(b.position);const [w,x,y,z]=b.quaternion;group.quaternion.set(x,y,z,w);bodyGroups.get(b.parent).add(group);bodyGroups.set(b.id,group);
  for(const joint of b.joints){const row=document.createElement('div');row.className='joint';const label=document.createElement('label');const span=document.createElement('span');span.textContent=joint.name.replaceAll('_',' ');const output=document.createElement('output');const input=document.createElement('input');input.type='range';input.min=joint.range[0];input.max=joint.range[1];input.step='any';input.value=0;input.id='joint-'+joint.name;label.htmlFor=input.id;label.append(span,output);row.append(label,input);$('#joints').append(row);const item={group,joint,input,output,basePos:group.position.clone(),baseQuat:group.quaternion.clone()};jointControls.push(item);input.oninput=()=>setJoint(item,Number(input.value));setJoint(item,0)}
 }
 root.updateMatrixWorld(true);scene.add(g.scene);g.scene.updateMatrixWorld(true);g.scene.traverse(o=>{if(o.isMesh)items.push(o)});
 for(const mesh of items){const metadata=rig.meshes[mesh.name];if(!metadata)throw Error('Missing body mapping: '+mesh.name);bodyGroups.get(metadata.body).attach(mesh);mesh.material=mesh.material.clone();mesh.material.metalness=0;mesh.material.roughness=mesh.name.startsWith('brow_')?.32:.62;mesh.userData.base=mesh.position.clone();const world=mesh.getWorldPosition(new THREE.Vector3());const outward=new THREE.Vector3(world.x<0?-.06:.05,world.y<0?-.07:.07,.025);const q=mesh.parent.getWorldQuaternion(new THREE.Quaternion()).invert();mesh.userData.explode=outward.applyQuaternion(q)}
 scene.remove(g.scene);root.rotation.x=-Math.PI/2;
 $('#part-count').textContent=parts.length+'개';$('#mass').textContent=v.added_mass_g.toFixed(1)+' g';$('#check-status').textContent=`CAD ${parts.length}개 부품의 STL은 닫힌 메시이며 STEP이 제공됩니다. 원본 14개 제어 관절의 순서와 범위를 비교했습니다. 자세 조절은 해당 축을 이용한 시각 시연입니다.`;
 for(const p of parts){const tr=document.createElement('tr');const name=document.createElement('td');const button=document.createElement('button');button.textContent=p.name.replaceAll('_',' ');button.onclick=()=>{select(items.find(m=>m.name===p.name));$('#workshop').scrollIntoView({behavior:'smooth'})};name.append(button);tr.append(name);for(const text of [p.dimensions_mm.map(n=>n.toFixed(1)).join(' × '),p.mass_g.toFixed(2)+' g']){const td=document.createElement('td');td.textContent=text;tr.append(td)}const files=document.createElement('td');for(const [label,path] of [['STL',`models/print/${p.name}.stl`],['STEP',p.step]]){const a=document.createElement('a');a.textContent=label+' ↓';a.href='../'+path;files.append(a)}tr.append(files);$('#part-list').append(tr)}
 $('#status').hidden=true;window.microRexLoaded=true;window.microRex={items,jointControls,root,select,scene,camera,renderer,controls,bodyGroups,rig};
}catch(e){$('#status').textContent='모델 로딩에 실패했습니다. 새로고침하거나 GitHub에서 파일을 확인해 주세요.';console.error(e)}
$('#explode').onclick=e=>{expanded=!expanded;applyExplode();e.target.textContent=expanded?'조립 상태로 보기':'부품 분해해서 보기';e.target.setAttribute('aria-pressed',expanded)};
$('#stock').onclick=e=>{hideStock=!hideStock;items.forEach(o=>{if(o.name.startsWith('stock_'))o.visible=!hideStock});e.target.textContent=hideStock?'원본 부품 보이기':'원본 부품 숨기기';e.target.setAttribute('aria-pressed',hideStock)};
$('#rotate').onclick=e=>{controls.autoRotate=!controls.autoRotate;e.target.textContent=controls.autoRotate?'자동 회전 끄기':'자동 회전 켜기';e.target.setAttribute('aria-pressed',controls.autoRotate)};
$('#camera').onchange=e=>{const poses={perspective:[.48,.35,.55],side:[0,.19,.75],front:[.75,.19,0],top:[0,.85,.001]};camera.position.fromArray(poses[e.target.value]);controls.target.set(-.02,.15,0);controls.update()};
$('#reset').onclick=()=>{jointControls.forEach(j=>setJoint(j,0));if(expanded)$('#explode').click();if(hideStock)$('#stock').click();if(controls.autoRotate)$('#rotate').click();select(null);$('#selection').innerHTML='<h3>부품을 선택하세요</h3><p>모델이나 아래 목록에서 선택하면 제작 파일을 볼 수 있습니다.</p>';$('#camera').value='perspective';$('#camera').dispatchEvent(new Event('change'))};
$('#snapshot').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.download='micro-rex-kinematic-view.png';a.href=renderer.domElement.toDataURL('image/png');a.click()};
const raycaster=new THREE.Raycaster();let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY]});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=raycaster.intersectObjects(items.filter(m=>m.visible),false)[0];if(hit)select(hit.object)});
new ResizeObserver(()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}).observe(el);
let replay=null,replayStart=0,replayVersion=0;
function stopReplay(){replayVersion++;replay=null;$('#policy-play').textContent='시뮬레이션 기록 재생';jointControls.forEach(j=>j.input.disabled=false);if(rig){const b=rig.bodies.find(b=>b.parent===0),g=bodyGroups.get(b.id);g.position.fromArray(b.position);const[w,x,y,z]=b.quaternion;g.quaternion.set(x,y,z,w)}items.forEach(o=>o.visible=!(hideStock&&o.name.startsWith('stock_')))}
function applyReplayFrame(index){const q=replay.qpos[index];const trunk=bodyGroups.get(rig.bodies.find(b=>b.parent===0).id);trunk.position.fromArray(q.slice(0,3));trunk.quaternion.set(q[4],q[5],q[6],q[3]);for(let j=0;j<replay.joint_names.length;j++){const item=jointControls.find(c=>c.joint.name===replay.joint_names[j]);if(item)setJoint(item,q[7+j])}controls.target.set(q[0],q[2]+.04,-q[1]);camera.position.x=q[0]+.48;camera.position.z=-q[1]+.55;}
$('#policy-play').onclick=async()=>{if(replay){stopReplay();$('#reset').click();$('#policy-status').textContent='기록 재생을 중지했습니다.';return}const version=++replayVersion;$('#policy-status').textContent='실제 계산 기록을 불러오는 중…';try{const r=await fetchJSON('../artifacts/policy_replay_'+$('#policy-model').value+'.json');if(version!==replayVersion)return;$('#reset').click();replay=r;replayStart=performance.now();applyReplayFrame(0);jointControls.forEach(j=>j.input.disabled=true);const reference=$('#policy-model').value==='microduck';items.forEach(o=>o.visible=!reference||o.name.startsWith('stock_'));$('#policy-play').textContent='재생 중지';$('#policy-status').textContent=`전진 명령 0.3 m/s · ${r.result.duration_s}초 기록 · 실제 계산 이동 X ${r.result.final_xy_m[0].toFixed(2)} m · 실물 미검증`;}catch(e){$('#policy-status').textContent='기록을 불러오지 못했습니다.';console.error(e)}};
$('#policy-model').onchange=()=>{stopReplay();$('#reset').click()};
const manualReset=$('#reset').onclick;$('#reset').onclick=()=>{stopReplay();manualReset()};
let inView=true,lastFrame=0;new IntersectionObserver(entries=>{inView=entries[0].isIntersecting}).observe(el);
renderer.setAnimationLoop(time=>{if(document.hidden||time-lastFrame<33)return;lastFrame=time;if(replay){const i=Math.min(replay.qpos.length-1,Math.floor((time-replayStart)/1000/replay.dt));applyReplayFrame(Math.max(0,i));}controls.update();if(inView)renderer.render(scene,camera)});
